<?php

/**
 * Created by PhpStorm.
 * User: Nimo
 * Date: 08/08/2016
 * Time: 10:05 CH
 */
class index_model extends base_model
{
    public $table = "posts";

    public function getAll($table = null)
    {
        return parent::getAll($this->table); // TODO: Change the autogenerated stub
    }

    public function getTotalPost()
    {
        $sql = "SELECT count(*) as total_post FROM " . $this->table;
        try {
            $this->stmt = $this->conn->prepare($sql);
            $this->stmt->execute();
        } catch (PDOException $exc) {
            die($exc->getMessage());
        }
        return $this->stmt->fetch();
    }

    public function getData($limit, $page)
    {
        $sql = "SELECT posts.*, users.user_name FROM posts INNER JOIN users ON posts.user_ID = users.id";
        try {
            if ($limit !== 'all') {
                $sql .= " LIMIT " . (($page - 1) * $limit) . "," . $limit;
            }
            $this->stmt = $this->conn->prepare($sql);
            $this->stmt->execute();
        } catch (PDOException $exc) {
            die($exc->getMessage());
        }
        return $this->stmt->fetchAll();
    }
}